"""
AI Engine Module
Wraps PandasAI to provide natural language querying and chart generation.

Security considerations:
- PandasAI generates and executes LLM-produced code
- Charts are saved to a controlled directory
- API key is loaded from Streamlit secrets (never hardcoded)

Note: PandasAI 2.0.24 has a known bug where save_charts=True causes
'PipelineContext has no attribute prompt_id'. We work around this by
disabling save_charts and intercepting matplotlib's plt.show() to
save charts ourselves.
"""

import os
import time
import uuid
import pandas as pd
import streamlit as st
import matplotlib
import matplotlib.pyplot as plt
from typing import Any, Tuple, Optional


# Directory for saving generated charts
CHARTS_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "exports", "charts")


def get_api_key() -> str:
    """
    Retrieve OpenAI API key from Streamlit secrets.
    Raises an error if not configured.
    """
    try:
        api_key = st.secrets["OPENAI_API_KEY"]
        if api_key == "your-openai-api-key-here" or not api_key:
            raise ValueError("API key is not configured.")
        return api_key
    except (KeyError, FileNotFoundError):
        raise ValueError(
            "OpenAI API key not found. Please add it to `.streamlit/secrets.toml`:\n\n"
            '```\nOPENAI_API_KEY = "sk-your-key-here"\n```'
        )


def create_smart_df(df: pd.DataFrame) -> Any:
    """
    Wrap a pandas DataFrame with PandasAI SmartDataframe.

    Configures:
    - OpenAI model (configurable via secrets.toml)
    - save_charts DISABLED to avoid PandasAI 2.0.24 prompt_id bug
    - Chart saving handled manually via matplotlib hook
    - Verbose mode off for cleaner output
    """
    from pandasai import SmartDataframe
    from pandasai.llm import OpenAI

    api_key = get_api_key()

    # Ensure charts directory exists
    os.makedirs(CHARTS_DIR, exist_ok=True)

    # Model is configurable via .streamlit/secrets.toml (OPENAI_MODEL)
    # Defaults to gpt-3.5-turbo if not specified
    model = st.secrets.get("OPENAI_MODEL", "gpt-3.5-turbo")
    llm = OpenAI(api_token=api_key, model=model)

    sdf = SmartDataframe(
        df,
        config={
            "llm": llm,
            "save_charts": False,       # DISABLED — buggy in 2.0.24
            "save_charts_path": CHARTS_DIR,
            "verbose": False,
            "enable_cache": True,
            "open_charts": False,
        },
    )
    return sdf


def _patch_plt_show():
    """
    Monkey-patch plt.show() so that any chart generated by PandasAI's
    LLM-produced code gets saved to disk instead of displayed.
    Returns a dict that will contain the saved chart path after the query.
    """
    result = {"chart_path": None}

    # Use non-interactive backend so plt.show() doesn't block
    matplotlib.use("Agg")

    _original_show = plt.show

    def _saving_show(*args, **kwargs):
        # Save all open figures
        for fig_num in plt.get_fignums():
            fig = plt.figure(fig_num)
            chart_name = f"chart_{uuid.uuid4().hex[:8]}.png"
            chart_path = os.path.join(CHARTS_DIR, chart_name)
            fig.savefig(chart_path, dpi=150, bbox_inches="tight",
                        facecolor="#0E1117", edgecolor="none")
            result["chart_path"] = chart_path
        plt.close("all")

    plt.show = _saving_show
    return result, _original_show


def _restore_plt_show(original_show):
    """Restore the original plt.show()."""
    plt.show = original_show


def ask_question(smart_df: Any, question: str) -> Tuple[str, Optional[str], str]:
    """
    Ask a natural language question about the data.

    Returns:
        Tuple of (response_text, chart_path_or_none, response_type)
        response_type is one of: 'text', 'dataframe', 'chart', 'error'
    """
    try:
        # Ensure charts dir exists
        os.makedirs(CHARTS_DIR, exist_ok=True)

        # Patch plt.show to capture chart output
        chart_result, original_show = _patch_plt_show()

        try:
            response = smart_df.chat(question)
        finally:
            _restore_plt_show(original_show)

        # PandasAI always saves charts as "temp_chart.png", causing overwrites.
        # Rename to a unique filename immediately after each query.
        temp_chart = os.path.join(CHARTS_DIR, "temp_chart.png")
        renamed_chart = None
        if os.path.exists(temp_chart):
            unique_name = f"chart_{uuid.uuid4().hex[:8]}.png"
            renamed_chart = os.path.join(CHARTS_DIR, unique_name)
            os.rename(temp_chart, renamed_chart)

        # Check if a chart was saved by our patched plt.show()
        chart_path = chart_result.get("chart_path")

        # Use the renamed PandasAI chart if our hook didn't capture one
        if not chart_path and renamed_chart:
            chart_path = renamed_chart

        # Fallback: check for any recent chart in the directory
        if not chart_path:
            chart_path = _find_latest_chart()

        if chart_path and os.path.exists(chart_path):
            response_text = str(response) if response else "Here's the generated chart:"
            return response_text, chart_path, "chart"

        # Check if response is a DataFrame
        if isinstance(response, pd.DataFrame):
            return response.to_string(), None, "dataframe"

        # Plain text response
        response_text = str(response) if response is not None else "No response generated."
        return response_text, None, "text"

    except Exception as e:
        error_msg = str(e)

        # Provide user-friendly error messages
        if "AuthenticationError" in error_msg or "api_key" in error_msg.lower():
            return "❌ API key is invalid or expired. Please check your OpenAI API key.", None, "error"
        elif "RateLimitError" in error_msg or "rate_limit" in error_msg.lower():
            return "⏳ Rate limit reached. Please wait a moment and try again.", None, "error"
        elif "timeout" in error_msg.lower():
            return "⏱️ Request timed out. Please try a simpler question.", None, "error"
        else:
            return f"❌ Error: {error_msg}", None, "error"


def _find_latest_chart() -> Optional[str]:
    """
    Find the most recently created chart in the exports directory.
    Returns the file path if a new chart was created, None otherwise.
    """
    if not os.path.exists(CHARTS_DIR):
        return None

    chart_files = []
    for f in os.listdir(CHARTS_DIR):
        if f.lower().endswith((".png", ".jpg", ".jpeg", ".svg")):
            full_path = os.path.join(CHARTS_DIR, f)
            chart_files.append((full_path, os.path.getmtime(full_path)))

    if not chart_files:
        return None

    # Return the most recent chart
    chart_files.sort(key=lambda x: x[1], reverse=True)
    latest_path, latest_time = chart_files[0]

    # Only return if the chart was created in the last 30 seconds
    if time.time() - latest_time < 30:
        return latest_path

    return None


def get_suggested_questions(df: pd.DataFrame) -> list:
    """
    Generate suggested questions based on the DataFrame structure.
    These are static suggestions, not LLM-generated (to avoid extra API calls).
    """
    suggestions = []
    numeric_cols = df.select_dtypes(include=["number"]).columns.tolist()
    categorical_cols = df.select_dtypes(include=["object", "category"]).columns.tolist()

    if len(df) > 0:
        suggestions.append(f"How many rows are in this dataset?")

    if numeric_cols:
        col = numeric_cols[0]
        suggestions.append(f"What is the average {col}?")
        suggestions.append(f"Plot a histogram of {col}")

    if categorical_cols:
        col = categorical_cols[0]
        suggestions.append(f"What are the unique values in {col}?")

    if numeric_cols and categorical_cols:
        suggestions.append(
            f"Plot a bar chart of average {numeric_cols[0]} by {categorical_cols[0]}"
        )

    if len(numeric_cols) >= 2:
        suggestions.append(
            f"Plot a scatter plot of {numeric_cols[0]} vs {numeric_cols[1]}"
        )

    return suggestions[:5]  # Limit to 5 suggestions
